### ISSUE TITLE
Questions?

### ISSUE THREAD

**Issue by ericclemmons** [PatrickJS/redis-dataloader#1]
Hi!  I'm about to merge a PR in a work project using this, but wanted to confirm a few things...

For background, our project runs across several containers using `DataLoader` today.  Each container persists dataloaders for the duration of the process (which means we keep the in-memory cache between requests).

We were about to do a pass-through cache layer with Redis, when we stumbled on your fine project!

- This project maintains an in-memory cache.  When you `.clear(id)`, other containers' dataloaders won't know about this.  Is the in-memory cache a stale cache (for when redis fails), or is it the 1st goto and redis is the fall back?
- With this being said, does the in-memory cache create problems when there's not a single process running?
- `.clearAll` isn't supported, but it's possible to `Promise.all` clear all keys matching the loader namespace.  

Great work on this project!  I wanted to throw some of my thoughts out here to ensure I'm not running into what may be obvious problems to you.

**Comment by MychaelZ** [comment]
The author no longer maintains this due to the plethora of bugs.

**Comment by DubFriend** [comment]
- The local in-memory cache is the 1st goto, with redis as the fallback
- I'm not sure if the in-memory cache causes problems if there isnt a single process running, I haven't experienced any issues. You could disable the in memory caching if you wanted as well 

```js
const loader = new RedisDataLoader('prefix', new DataLoader(..., { cache: false }), { cache: false })
```
- I left out `.clearAll` because I couldn't see a way to implement this against redis without using the redis "KEYS" command (which locks up the whole redis database while it is running and can cause serious performance issues in production).

Thanks 😄
